apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd2
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080  # 클러스터 외부에서 접근할 포트 (30000-32767 사이에서 선택)
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30443  # 클러스터 외부에서 접근할 포트
  type: NodePort

